name: geeco
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  scaled_size: ^0.5.1
  provider: ^6.1.5+1
  envied: ^1.3.1
  lazy_load_indexed_stack: ^1.2.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  fluttertoast: ^8.0.0
  dynamic_widget: ^6.0.0
  gal: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^1.3.1
  build_runner: ^2.9.0

flutter:
  assets:
    - assets/images/
    - assets/images/aboutus_bg.jpg
    - assets/images/homepage_bg.png
    - assets/images/bax.jpg
    - assets/images/fabio.jpg
    - assets/images/ghen.jpg
    - assets/images/default_backdrops/backdrops/
    - assets/images/habitat_objects/Animal/
    - assets/images/habitat_objects/Land/
    - assets/images/habitat_objects/Water/
    - assets/images/logo.png
    - assets/images/dhblogo.png
    - assets/images/ecolenslogo.png
    - assets/images/score_icons/
    
  fonts:
    - family: Gabarito
      fonts:  
        - asset: assets/fonts/gabarito_variable.ttf
  uses-material-design: true
